import os
import json
from typing import Dict, Any, List

class RemotionExporter:
    def __init__(self, output_dir: str):
        self.output_dir = output_dir

    def export(self, edit_analysis: Dict[str, Any]) -> str:
        """
        Exports remotion_events.ts containing strongly-typed TypeScript timeline data
        and Remotion helper functions.
        """
        ts_path = os.path.join(self.output_dir, "remotion_events.ts")
        master_timeline = edit_analysis.get("masterTimeline", [])

        events_array = []
        for item in master_timeline:
            f = item.get("frame", 0)
            rel = item.get("relationship", "isolated_event")
            for ev in item.get("events", []):
                events_array.append({
                    "frame": f,
                    "time": item.get("time", 0.0),
                    "type": ev.get("type", "event"),
                    "relationship": rel,
                    "data": ev
                })

        ts_code = f"""// Generated by project_video_analyze (Edit Reverse-Engineering System)
// Temporal Source of Truth for Remotion Composition Sync

export interface AnalyzedEvent {{
  frame: number;
  time: number;
  type: string;
  relationship: string;
  data: Record<string, any>;
}}

export const editEvents: AnalyzedEvent[] = {json.dumps(events_array, indent=2)};

export function getNearestBeat(frame: number): AnalyzedEvent | undefined {{
  const beats = editEvents.filter(e => e.type.includes("beat"));
  if (beats.length === 0) return undefined;
  return beats.reduce((prev, curr) => 
    Math.abs(curr.frame - frame) < Math.abs(prev.frame - frame) ? curr : prev
  );
}}

export function getNearestOnset(frame: number): AnalyzedEvent | undefined {{
  const onsets = editEvents.filter(e => e.type.includes("onset"));
  if (onsets.length === 0) return undefined;
  return onsets.reduce((prev, curr) => 
    Math.abs(curr.frame - frame) < Math.abs(prev.frame - frame) ? curr : prev
  );
}}

export function getEventsAtFrame(frame: number): AnalyzedEvent[] {{
  return editEvents.filter(e => e.frame === frame);
}}

export function getEventsBetweenFrames(startFrame: number, endFrame: number): AnalyzedEvent[] {{
  return editEvents.filter(e => e.frame >= startFrame && e.frame <= endFrame);
}}

export function getEditingPattern(frame: number): string {{
  const ev = editEvents.find(e => e.frame === frame);
  return ev ? ev.relationship : "isolated_event";
}}
"""
        with open(ts_path, "w", encoding="utf-8") as f:
            f.write(ts_code)

        return ts_path
